name: cocktaildb
description: TheCocktailDB API client.
version: 1.0.0
homepage: https://github.com/thechampagne/cocktaildb-dart
repository: https://github.com/thechampagne/cocktaildb-dart
documentation: https://pub.dev/documentation/cocktaildb/latest/

environment:
  sdk: '>=2.17.5 <3.0.0'
